name: CI - Backend Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.15'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Instalar dependencias
        run: npm ci
        working-directory: ./backend

      - name: Auditoría de Seguridad
        run: npm audit --audit-level=high
        working-directory: ./backend

      - name: Generar Cliente Prisma
        run: npx prisma generate
        working-directory: ./backend
        env:
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"

        
      - name: Verificar Tipado (TS)
        run: npx tsc --noEmit
        working-directory: ./backend

      - name: Linter (Validación de reglas y 'any')
        run: npm run lint
        working-directory: ./backend

      - name: Ejecutar Pruebas
        run: npm test
        working-directory: ./backend
        env:
          PORT: 3000
          DATABASE_URL: "postgresql://dummy:dummy@localhost:5432/dummy"
          NODE_ENV: test